[theme]
base="dark"
primaryColor="#FFD700"         # Gold
backgroundColor="#0E0E0E"      # True black
secondaryBackgroundColor="#1A1A1A"  # Slightly lighter black
textColor="#FFFFFF"
font="sans serif"
